matrix:
  include:
    - language: python
      python:
        - "2.7"
        - "3.6"
      # command to install dependencies
      install:
        - wget https://github.com/apdavison/pyxus/archive/list-fixes.zip
        - unzip list-fixes.zip
        - pip install -r pyxus-list-fixes/pyxus/requirements.txt
        - pip install pyxus-list-fixes/pyxus
        - pip install ./client
        - pip install nose coverage
      # command to run tests
      script:
        - nosetests --with-coverage --cover-package=nar --cover-html ./client
    - language: node_js
      node_js:
        - "node"
        - "9"
      # before_script:
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      install:
        - cd apps/nar-browser
        - npm install
      script:
        - ./node_modules/.bin/karma start --browsers Firefox --single-run 
    
