matrix:
  include:
    - language: python
      python:
        - "2.7"
        - "3.6"
      # command to install dependencies
      install:
        - wget https://github.com/HumanBrainProject/pyxus/archive/master.zip
        - unzip master.zip
        - pip install -r pyxus-master/pyxus/requirements.txt
        - pip install pyxus-master/pyxus
        - pip install ./client
        - pip install nose coverage pathlib2
      # command to run tests
      script:
        - nosetests --with-coverage --cover-package=nar --cover-html ./client
    - language: node_js
      node_js:
        - "node"
        - "9"
      addons:
        chrome: stable
      # before_script:
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      install:
        - cd apps/nar-browser
        - npm install
      script:
        - ./node_modules/.bin/karma start --browsers Chrome_travis_ci --single-run 
    
